# Generated by Django 5.2.8 on 2025-11-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_messengeruser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengeruser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
