# Generated by Django 5.2.8 on 2025-11-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_chat_textmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='date_of_sending',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
