# Generated by Django 5.2.8 on 2025-12-04 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_textmessage_date_of_sending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textmessage',
            options={'ordering': ['date_of_sending'], 'verbose_name': 'Текстовое сообщение', 'verbose_name_plural': 'Текстовые сообщения'},
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.chat'),
        ),
    ]
