# Generated by Django 5.2.8 on 2025-12-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_textmessage_options_chat_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user2',
        ),
    ]
