# Generated by Django 5.2.8 on 2025-12-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_chat_user1_remove_chat_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='Chat', max_length=150, verbose_name='Название чата'),
        ),
    ]
