# Generated by Django 5.2.8 on 2025-12-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_chat_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='iv',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
