# Generated by Django 5.2.8 on 2025-12-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_textmessage_iv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='iv',
            field=models.CharField(max_length=24),
        ),
    ]
